Update make

diff --git a/scripts/make b/scripts/make
--- a/scripts/make
+++ b/scripts/make
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -e
 
 CT_URL_GNU="https://github.com/cross-tools"
 CT_URL_MUSL="https://github.com/Matrix3600"
 CT_VER_GNU=20260430
-CT_VER_MUSL=20260511
+CT_VER_MUSL=20260515
 LLVM_TARGETS="AArch64;ARM;LoongArch;Mips;PowerPC;RISCV;SystemZ;X86"
 
 install_packages()
@@ -50,7 +50,7 @@ build_llvm()
 
 build_target()
 {
-	TARGET=${1}
+	TARGET=$1
 	. targets/${TARGET}/config
 	sudo rm -rf build
 	mkdir build
@@ -120,12 +120,22 @@ build_target()
 	sudo rm -rf build
 }
 
+if [ -z "$1" ]; then
+	echo "Target is missing."
+	exit 1
+fi
+
+if [[ $1 != "llvm" && ! -f "targets/$1/config" ]]; then
+	echo "Target not supported ($1)."
+	exit 1
+fi
+
 install_packages
 
-if [ ! -e clang-cross.tar.xz ]; then
+if [ ! -f "clang-cross.tar.xz" ]; then
 	build_llvm
 fi
 
-if [ "${1}" != "llvm" ]; then
-	build_target ${1}
+if [ "$1" != "llvm" ]; then
+	build_target $1
 fi
