Pre-download source packages at start of workflows

diff --git a/scripts/make b/scripts/make
--- a/scripts/make
+++ b/scripts/make
@@ -129,6 +129,20 @@ function build_target()
 	local llvm_version
 	llvm_version="$(get_llvm_version)"
 
+	local src_dir="$CROSS_CLANG_SOURCE_DIR"
+	if [ -z "$src_dir" ]; then
+		src_dir="source-tarballs"
+	fi
+	set +e
+	local source_dir="$(mkdir -p -- "$src_dir" &>/dev/null && \
+		cd -- "$src_dir" &>/dev/null && pwd)"
+	set -e
+	if [ -z "$source_dir" ]; then
+		echo "[ERROR] Source directory invalid (${src_dir})." >&2
+		return 1
+	fi
+	export CROSS_CLANG_TARGET_SOURCE_DIR="$source_dir"
+
 	sudo rm -rf build
 	mkdir build
 	pushd build
@@ -196,15 +210,18 @@ else
 				break
 			fi
 		done
-		if [[ -z $DEFAULT_TARGET && $TARGET != "llvm" ]]; then
-			DEFAULT_TARGET=$TARGET
-		fi
 	fi
 fi
 
 if [[ $CROSS_CLANG_RESUME == "true" && ! -f "$llvm_tarname" ]]; then
 	url="${CROSS_CLANG_URL}/clang-cross/releases/download/${CROSS_CLANG_LATEST}/${llvm_tarname}"
 	wget -nv -nc -T 120 --tries=20 "$url" 2>/dev/null || true
+fi
+
+if [[ -z $DEFAULT_TARGET && ! -f "$llvm_tarname" && \
+		$TARGET != "sysroot" && $TARGET != "llvm" ]]; then
+	DEFAULT_TARGET=$TARGET
+	llvm_tarname="${llvm_prefix}_${DEFAULT_TARGET}.tar.xz"
 fi
 
 if [ ! -f "$llvm_tarname" ]; then
